# Project: exeTobin
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../Exec/main.o
LINKOBJ  = ../../Exec/main.o
LIBS     = -L"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/lib" -L"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/include" -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/include" -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/utilisateur/Desktop/DevC++Port/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = exeTobin.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = E:\utilisateur\Desktop\DevC++Port\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../Exec/main.o: ../../Exec/main.cpp
	$(CPP) -c ../../Exec/main.cpp -o ../../Exec/main.o $(CXXFLAGS)
